### ISSUE TITLE
Missing Protocol 77379 (4.11 Patch) 

### ISSUE THREAD

**Issue by amartin916** [Blizzard/s2protocol#100]
This patch had enough changes from the previous version, that the previous protocol file does not work .

**Comment by ZephyrBlu** [comment]
It's a shame there's no go-to developer at Blizzard we can talk to about issues like this :/

**Comment by Talv** [comment]
I'm pretty sure previous maintainer of this repo was either reassigned to different project (Diablo?) or simply quit? And no one took over since then...

And yes, this patch appears to be pretty massive in terms of changes. Specifically `initData`: it seems they introduced plenty of new fields that correlate with BrutalPlus from co-op mode.

In my test sample of the same map with 2 players in game, `initData` file grew in size by about 20% (previous patch 708 bytes, current patch 879 bytes).

I've been trying to reverse engineer it, but it's just too much [1] to be worth the time. Gotta be patient I guess...

[1]
```cs
NNet::Game::SLobbySlotChange::_typeof_m_control
NNet::Game::SLobbySlotChange::_typeof_m_userId
NNet::Game::SLobbySlotChange::_typeof_m_teamId
NNet::Game::SLobbySlotChange::_typeof_m_colorPref
NNet::Game::SLobbySlotChange::_typeof_m_racePref
NNet::Game::SLobbySlotChange::_typeof_m_difficulty
NNet::Game::SLobbySlotChange::_typeof_m_aiBuild
NNet::Game::SLobbySlotChange::_typeof_m_handicap
NNet::Game::SLobbySlotChange::_typeof_m_observe
NNet::Game::SLobbySlotChange::_typeof_m_logoIndex
NNet::Game::SLobbySlotChange::_typeof_m_hero
NNet::Game::SLobbySlotChange::_typeof_m_skin
NNet::Game::SLobbySlotChange::_typeof_m_mount
NNet::Game::SLobbySlotChange::_typeof_m_licenses
NNet::Game::SLobbySlotChange::_typeof_m_tandemLeaderId
NNet::Game::SLobbySlotChange::_typeof_m_commander
NNet::Game::SLobbySlotChange::_typeof_m_commanderLevel
NNet::Game::SLobbySlotChange::_typeof_m_hasSilencePenalty
NNet::Game::SLobbySlotChange::_typeof_m_tandemId
NNet::Game::SLobbySlotChange::_typeof_m_commanderMasteryLevel
NNet::Game::SLobbySlotChange::_typeof_m_brutalPlusDifficulty
NNet::Game::SLobbySlotChange::_typeof_m_retryMutationIndexes
NNet::Game::SLobbySlotChange::_typeof_m_aCEnemyRace
NNet::Game::SLobbySlotChange::_typeof_m_aCEnemyWaveType
```

**Comment by amartin916** [comment]
File has been added, thank you for the quick turn around!
