### ISSUE TITLE
For teams: any way of knowing the team leagues, and/or wether or not the team is arranged?

### ISSUE THREAD

**Issue by flyrev** [Blizzard/s2protocol#21]
I know each each player has a highest_league, but that's only for their 1v1 ladder rank. 

For teams games, though, I would like to know:
- Are the teams arranged or random?
- For random teams, which random league is each player? I'm looking for something that would give me 'random 3v3 bronze, random 3v3 silver and random 3v3 diamond'.
- For arranged teams, which league is each team?

Are these things currently available in the replays at all, or does one have to resort to scraping to get this information?

**Comment by jrepp** [comment]
Good questions. There is some information in the --initdata section such as highestLeague. The team selection is done through some trickery known as the grouping attribute which is a fairly abstract concept provided through attributes. This may look slightly different for matchmade vs. custom melee games. It might be easier to just dump this information in the --metdata section instead of asking anyone to try to reverse it through attribute ID selection.

**Comment by jrepp** [comment]
I added much better support for parsing attributes on the dev branch. It might be worth revisiting this issue with the grouping attributes.

**Comment by flyrev** [comment]
Any update on this?
